title: Skoggy Games
email: skoggy@skoggygames.com
description: >
  Skoggy Games makes video games like Puck Off

baseurl: ""
url: ""
twitter_username: erikskogl
github_username:  eriksk
copyright: Copyright &copy Erik Skoglund - Skoggy Games 2017

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
